### ISSUE TITLE
Trakt.tv intergration

### ISSUE THREAD

**Issue by dvdgorila** [Ferrite-iOS/Ferrite#9]
Hello, 

Thanks for making this app available! 
Was wondering if you had any plans to traktv support similar to the wako app?

Thanks, 
Dvdgorila

**Comment by kingbri1** [comment]
Hi there, I was previously looking into this feature that makes using Ferrite better than the Trakt app (scrobbling, etc).

Due to having no implemented player, Ferrite will not be able to reliably sync or update Trakt based on watchtime. I would recommend using infuse's Trakt integration.

Wako also does not support trakt on iOS even though it says it does based on my testing. It's probably an android feature that the dev did not turn off for the iOS version.

Closing this issue.

**Comment by dvdgorila** [comment]
Oh, i shouldve clarified, i meant as means to add media for lookup and add to real-debrid 
It does work on the iOS version. The way i use it is i have my trakt list (mine and liked list) If i click on something, it brings up the releases which I can then add to real-debrid.

**Comment by kingbri1** [comment]
This feature is pretty redundant considering the trakt app has a better UI and integration (since it's official). Not to mention that there are other shows and providers such as Anilist, MAL, TMDB, etc. Ferrite is a decentralized search engine, so a descriptive search query will get you to the right show, quality, group, etc. Use the right app for the right purpose.

The only reason I'd add support for tracking is if I can automatically update entries, which I can't due to no player being present.

The next version will also contain bookmarks and history so you can save and see what you have watched. Therefore, I am keeping this issue closed.
